apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
spec:
  generators:
  - git:
      repoURL: https://github.com/satishbpatil/control-plane
      revision: HEAD
      directories:
      - path: "workload/*"
  template:
    metadata:
      name: 'workload-{{path.basename}}'
    spec:
      project: default
      source:
        helm:
          ignoreMissingValueFiles: true
          values: |
            workloadName: "{{path.basename}}"          
          valueFiles:
          - '../workload/{{path}}/repo.json'
        repoURL: 'https://github.com/satishbpatil/control-plane'
        path: charts/workload
        targetRevision: HEAD
      destination:
        namespace: 'argocd'
        name: 'in-cluster'
      syncPolicy:
        automated: {}